# dataset settings
dataset: 'cifar10'
pretext_task: 'rotation'
resized_img_size: 32
batch_size: 128

# experiment settings
experiment: 'downstream-random'
downstream_epochs: 100
dataset_mode: 'validation'
val_split: 0.2

# set the folder where you want to store the results
dir_main_results: C:\Users\t.devries\Documents\GitHub\PolarSSL\results\

# pretext task hyperparameters
pretext:
  weight_decay:

# downstream task hyperparameters
downstream:
  weight_decay:
    - 0.1
    - 0.01
    - 0.001
  momentum:
    - 0.9
    - 0.09
    - 0.009
  learning_rate:
    - 0.1
    - 0.01
    - 0.001
