# dataset settings
dataset: 'cifar10'
pretext_task: 'rotation'
resized_img_size: 32
batch_size: 128

# experiment settings
experiment: 'evaluate-test-self-supervised'
dataset_mode: 'test'

# set the folder where you want to store the results
dir_main_results: C:\Users\t.devries\Documents\GitHub\PolarSSL\results\

# supervised evaluation
#downstream_weights_file: C:\Users\t.devries\Documents\GitHub\PolarSSL\results_thesis\2023-06-10_11-03_rotation_cifar10_supervised\w_0.01\m_0.9\lr_0.01\downstream_weights.hdf5

# random evaluation
downstream_weights_file: C:\Users\t.devries\Documents\GitHub\PolarSSL\results_thesis\2023-06-12_10-00_rotation_cifar10_downstream-random\w_0.01\m_0.9\lr_0.001\downstream_weights.hdf5

# self-supervised evaluation
#downstream_weights_file: C:\Users\t.devries\Documents\GitHub\PolarSSL\results_thesis\2023-06-07_11-11_rotation_cifar10_both\w_0.01\m_0.09\lr_0.1\downstream_weights.hdf5
#pretext_weights_file: C:\Users\t.devries\Documents\GitHub\PolarSSL\results_thesis\2023-06-07_11-11_rotation_cifar10_both\w_0.01\m_0.09\lr_0.1\pretext_weights.hdf5

# pretext task hyperparameters
pretext:
  weight_decay:

# downstream task hyperparameters
downstream:
  weight_decay:
