# dataset settings
dataset: 'eurosat'
dir_dataset: C:\Users\t.devries\Documents\Datasets\EuroSAT\2750
pretext_task: 'scale'
resized_img_size: 32
batch_size: 64

# experiment settings
experiment: 'effect-pretext'
pretext_epochs: 100
downstream_epochs: 100
dataset_mode: 'validation'
val_split: 0.2

# set the folder where you want to store the results
dir_main_results: C:\Users\t.devries\Documents\GitHub\PolarSSL\results\

# pretext task hyperparameters
pretext:
  weight_decay:

# downstream task hyperparameters
downstream:
  weight_decay:
    - 0.01
  momentum:
    - 0.09
  learning_rate:
    - 0.01
