batch_size: 64
dataset: eurosat
dataset_mode: validation
dir_dataset: C:\Users\t.devries\Documents\Datasets\EuroSAT\2750
dir_main_results: C:\Users\t.devries\Documents\GitHub\PolarSSL\results\
downstream:
  learning_rate:
  - 0.01
  momentum:
  - 0.09
  weight_decay:
  - 0.01
downstream_epochs: 100
experiment: effect-pretext
pretext:
  weight_decay: null
pretext_epochs: 100
pretext_task: scale
resized_img_size: 32
val_split: 0.2
